version: '2'
services:
    web:
        container_name: web
        build: .
        volumes:
            - ./tmp:/tmp
        command: uwsgi --ini myapp.ini
    nginx:
        container_name: nginx
        build: ./nginx
        depends_on:
            - web
        ports:
            - 80:80
        volumes:
            - ./tmp:/tmp
